class CommonConstant{
  static const String STATUS_SUCCESS = "SUCCESS";
  static const String STATUS_FAILED = "FAILED";
  static const String ACCOUNT_DOCTOR = "DOCTOR";
  static const String ACCOUNT_BUSINESS = "BUSINESS";
  static const String STATUS_CONFIRMED = "CONFIRMED";
  static const String STATUS_PENDING = "PENDING";
  static const String STATUS_VOID = "VOID";
  static const String FLAG_Y = "Y";
  static const String ENC_SALT = "nqoDqdzYoSFVuEhK8NdDVg==";
  static const String FLAG_N = "N";
  static const String SERVER_MSG = "Something went wrong,Please try again after sometime.";
  static const String EXISTS_FLAG_Y = "Y";
  static const String EXISTS_FLAG_N = "Y";
  static const String FOUND = "FOUND";
  static const String NOTFOUNT = "NOTFOUND";
  static const String OTP = "OTP";
  static const String ADMIN = "admin";
  static const String ALL_STATES = "ALL STATES";
  static const String ALL_CITIES = "ALL CITIES";
  static const String AMPAMT_EMAIL = "ampamt.india@gmail.com";
  static const String AMPAMT_CONTACTNO = "9930369699";
  static const String AMPAMT_HEAD_OFFICE_ADDRESS = "-";
  static const String AMPAMT_WORKING_HOUR = "11AM O'Clock To 5PM O'Clock";
  static const String AMPAMT = "AMPAMT";
  static const String ALL = "ALL";
  static const String ADVERTISEMENTS = "ADVERTISEMENTS";
  static const String NOTDATA = "NOTDATA";
  static const int AMPAMT_AMOUNT = 3000;
  static const String KEY_ID_LIVE = "rzp_live_RovxCktSDjNyUB";
  static const String KEY_ID_TEST = "rzp_test_rylpRjprBt4f6R";
  static const String PHONEPE = "PHONEPE";
  static const String PAYTM = "PAYTM";
  static const String GOOGLEPE = "GOOGLEPE";
  static const String SAVE = "SAVE";
  static const String DOWNLOAD = "DOWNLOAD";
  static const String VIEW = "VIEW";
  static const String EMAIL = "EMAIL";
  static const String OPEN = "OPEN";
  static const String PDF_EXTENSION = ".pdf";
  static const String APP_PACKAGE = "com.android.ampamt";
  static const String APP_PLAY_STORE_LINK = "https://play.google.com/store/apps/details?id=com.ampamt.ampamt";
  static const String START_OF_XLS_EXCEL_JSON="data:application/vnd.ms-excel;base64,";
  static const String START_OF_XLSX_EXCEL_JSON="data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,";
  static const String START_OF_PDF_JSON="data:application/pdf;base64,";
  static const String START_OF_IMAGE_BASE64="data:image/jpeg;base64,";
  static const String ANDROID_FOLDER="android";

}